**[Slide No. 5]**

1. Write a Program to check the version numpy installed .

In [1]:
import numpy
print(numpy.__version__)

1.20.1


**[Slide No . 8]**

2. Write a program to create numpy 1-D array from list.

In [2]:
import numpy as np
sample_list=[6,7,8,9,10,12]
b=np.array([sample_list])
b

array([[ 6,  7,  8,  9, 10, 12]])

**[Slide No. 9]**

3. Write a program to Create a 2-D array .

In [8]:
b.reshape(3,2)

array([[ 6,  7],
       [ 8,  9],
       [10, 12]])

In [13]:
A=np.array([1,8,3,4])

In [14]:
B = np.reshape(A, (-1, 2))
B

array([[1, 8],
       [3, 4]])

**[Slide No . 11]**

5. a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])



What is the output [5 9] ?

**[Slide No.15]**

6. Correct the program .

import numpy as np

array=np.array([1,2,3,4,5,6])

print(array[-1:-5])

In [3]:
array = np.array([1,2,3,4,5,6])

print(array[-4:-1])

[3 4 5]


7. a=np.array([(1,5,9),(10,12,2),(5,7,8)])


Print the max value from first row ?

print min value from the first row ?

print the sum of all the element of second row ?




In [5]:
a=np.array([(1,5,9),(10,12,2),(5,7,8)])
a

array([[ 1,  5,  9],
       [10, 12,  2],
       [ 5,  7,  8]])

In [7]:
a[0].max()

9

In [8]:
a[1].min()

2

In [9]:
a[1].sum()

24

In [11]:
import numpy as np
np1=np.random.randint(2,9,(3,2,3,4))
np1


array([[[[2, 8, 6, 4],
         [7, 6, 3, 8],
         [2, 3, 2, 2]],

        [[5, 7, 3, 7],
         [4, 7, 3, 2],
         [4, 6, 2, 4]]],


       [[[6, 7, 7, 5],
         [3, 3, 2, 8],
         [5, 6, 3, 6]],

        [[7, 6, 4, 6],
         [6, 3, 6, 3],
         [2, 5, 6, 5]]],


       [[[6, 8, 7, 4],
         [8, 3, 3, 4],
         [4, 4, 7, 2]],

        [[2, 5, 8, 6],
         [8, 2, 4, 3],
         [5, 2, 3, 4]]]])

In [16]:
np1[0][1]

array([[5, 7, 3, 7],
       [4, 7, 3, 2],
       [4, 6, 2, 4]])

**[Slide No. 16]**


8. Create a numpy array using a below numbers and print (1,3,5).

[1,2,3,4,5,6]




In [20]:
a=[1,2,3,4,5,6]
a[0:5:2]

[1, 3, 5]

In [ ]:
i%2==1

**[Slide No. 18]**

9. Create a  [3,4] numpy array and reshape it [4,3] numpy array.

In [25]:
b=np.random.rand(3,4)
b

array([[0.56867294, 0.10250926, 0.04663409, 0.6840817 ],
       [0.83732978, 0.39936573, 0.28511078, 0.42268473],
       [0.58535554, 0.3168733 , 0.15431376, 0.06583718]])

In [26]:
b.reshape(4,3)

array([[0.56867294, 0.10250926, 0.04663409],
       [0.6840817 , 0.83732978, 0.39936573],
       [0.28511078, 0.42268473, 0.58535554],
       [0.3168733 , 0.15431376, 0.06583718]])

**[Slide No. 20]**

10. Create two numpy array and concanate them .

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

**[Slide No.22]**

11. Create numpy array and search a number in it .

In [11]:
a=np.arange(0,5)
np.where(a==4)

(array([4], dtype=int64),)

**[Slide No.26]**

12. Write a program to print 3,4 numpy array by any random number using random.randint function

In [23]:
x=np.random.rand(3,4)
x

array([[0.40213394, 0.91198008, 0.08099068, 0.86472866],
       [0.67652221, 0.74518359, 0.12901953, 0.37443763],
       [0.53115907, 0.14953623, 0.19601372, 0.03519332]])

**[Slide No. 30]**

13. Write a program to add two numpy array.

14. Delete the second column from a given array and insert the following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

newColumn = numpy.array([[10,10,10]])

In [12]:
import numpy as np


In [16]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray, 1, axis = 0)
print(sampleArray)


[[34 43 73]
 [53 94 66]]


In [17]:
sampleArray = np.insert(sampleArray, 1, newColumn, axis = 0)
print(sampleArray)


[[34 43 73]
 [10 10 10]
 [53 94 66]]


In [7]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [8]:
sampleArray[:,1]=[10,10,10]

In [9]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])